name: LÖVE Potion

on: [push]

jobs:
  first:
    name: 3DS
    runs-on: ubuntu-latest

    container:
      image: docker://devkitpro/devkitarm
      options: --cpus 2

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build
        run: make ctr

      - uses: actions/upload-artifact@v2
        with:
          name: Nintendo 3DS
          path: |
            platform/3ds/*.elf
            platform/3ds/*.3dsx

  second:
    name: Switch
    runs-on: ubuntu-latest

    container:
      image: docker://devkitpro/devkita64
      options: --cpus 2

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build
        run: make hac

      - uses: actions/upload-artifact@v2
        with:
          name: Nintendo Switch
          path: |
            platform/switch/*.elf
            platform/switch/*.nro
