return {
	title = "Ok. ==>",
	pageId = 1678,
	timestamp = "1271388719",
	flag = {},
	media = {
		"01678",
	},
	content = {
		{
			0,
			0,
			0,
		},
		"I ",
		{
			0,
			0,
			0,
		},
		"CONJURE",
		{
			0,
			0,
			0,
		},
		" THIS INTREPID FANTASYSCAPE WITH TEARS BLED FROM THE WISDOM-WEARY EYES OF FIFTY THOUSAND IMAGINARY MAGICIANS. I PULL HEAVY DRAGS FROM THE BRUMES OF INSPIRATION WITH ENCHANTED BELLOWS MARAUDED FROM A GUILD OF CHURLISH MYTHICAL DWARVES. VAST BULBOUS RIDDLESPIDERS PUSH THE SILKEN STRANDS OF PURE WHIMSY THROUGH HIDEOUS ABDOMINAL SPINNERETS AND IT IS THAT WITH WHICH I WEAVE THIS AUDACIOUS COCOON OF EXQUISITE LIES. AND WHEN IT HATCHES A GREAT MOTH OF TITILLATION WILL AWAKEN AND ROAR AND BEAT ITS WINGS, AND THE POWDER SETTLING DOWN WILL ARREST THE HUMORS OF AN ENORMOUS TERRIBLE OLD BEGGAR, RELAXING THE VULTUROUS LEATHERY VICEGRIP HE'S FIXED AROUND YOUR CAPTIVE MIND.",
	},
	next = {
		1679,
	},
	previous = 1677,
}