return {
	title = "John: Collect grist, examine safe.",
	pageId = 542,
	timestamp = "1251346046",
	flag = {},
	media = {
		"00542",
	},
	content = {
		{
			0,
			0,
			0,
		},
		"You swoop up the bountiful supply of grist generated by your co-player's recent exploits. From now on it will probably go without saying that you'll nab any grist lying around without making a big fuss over it.",
		{
			0,
			0,
			0,
		},
		"\
\
You check out the busted SAFE, which has made a noble sacrifice in battle. Some of your father's odds and ends have spilled out, including some old NEWSPAPER CLIPPINGS, and two rather hefty TOMES. It's a fair bet that these books comprised at least half the weight of the safe.",
	},
	next = {
		543,
	},
	previous = 541,
}