return {
	title = "BUT THERE WAS ONE BADGE HE GOT.",
	pageId = 6248,
	timestamp = "1371079312",
	flag = {},
	media = {
		"06246",
	},
	content = {
		{
			0,
			0,
			0,
		},
		"THAT WAS NOT A PITIFUL WASTE OF HIS TIME. A SKELETON KEY BADGE. ",
		{
			0,
			0,
			0,
		},
		"\
\
HAVING THIS BADGE MEANT THAT HE COULD AUTOMATICALLY UNLOCK. ANY LOCK HE WANTED TO! ",
		{
			0,
			0,
			0,
		},
		"\
\
INCLUDING ALL THE CONTRAPTIONS ON THIS PLANET. ALLOWING HIM TO OFFICIALLY AND PERMANENTLY ASSUME CONTROL OF. A PROPERTY OF HIS EXPERIENTIAL CONTINUUM WHICH I HAVE REASON TO BELIEVE IS CALLED. \"THE NARRATIVE\".",
		{
			0,
			0,
			0,
		},
		"\
\
AND DUE TO HIS UNQUESTIONED SUPREMACY OVER A LOT OF THINGS. HE IS NOW ABLE TO COMMANDEER THIS ENIGMATIC MEDIUM. WHILE TOTALLY UNIMPEDED BY THE GHOSTLY VOICE OF A SARCASTIC DOUCHE.",
	},
	next = {
		6249,
	},
	previous = 6247,
	theme = "A6A6",
}