return {
	title = "IN MY DREAM. I AM THIS CHERUB.",
	pageId = 6249,
	timestamp = "1371079388",
	flag = {},
	media = {
		"06247",
	},
	content = {
		{
			0,
			0,
			0,
		},
		"IT'S ME. ",
		{
			0,
			0,
			0,
		},
		"\
\
AND AS IT HAPPENS. MY DREAM IS A *FACT*.",
		{
			0,
			0,
			0,
		},
		"\
\
I HAVE TAKEN OVER THIS \"STORY\". AND I WILL NOW RETELL IT ACCORDING TO MY UNDERSTANDING AND LEVEL OF INTEREST. I WILL ADDITIONALLY PROVIDE AN HONEST AND BRUTAL CRITIQUE OF THE EVENTS AND THE WAY THEY HAVE BEEN SHOWN. BY UTILIZING THE MOST POTENT WEAPON ANYONE COULD EVER HOPE TO ALLOCATE TO HIS SPECIBUS. IT IS THE WEAPON. OF \"SATIRE\".",
		{
			0,
			0,
			0,
		},
		"\
\
OH MY GOD. THIS IS GOING TO BE SO GREAT. HAS ANYONE EVER DONE ANYTHING LIKE THIS BEFORE??",
	},
	next = {
		6250,
	},
	previous = 6248,
	theme = "A6A6",
}