return {
	title = "MALE: GO OPEN THAT CHEST.",
	pageId = 6253,
	timestamp = "1371079666",
	flag = {},
	media = {
		"06251",
	},
	content = {
		{
			0,
			0,
			0,
		},
		"AND I TELL MY PUPPET WHAT TO DO. BY TYPING ORDERS IN THE THING. WHILE PRETENDING THAT *YOU* ARE TYPING THEM. IT IS A DISINGENUOUS RUSE AT BEST. TO MAKE YOU BELIEVE YOU ARE GUIDING MY PUPPET. WHILE ALSO BIZARRELY INSISTING THAT YOU *ARE* THE PUPPET, BY CALLING HIM YOU. I UNSUCCESSFULLY STRIVE TO IMMERSE YOU IN AN EXPERIENCE. THAT NO ONE WITH A BRAIN. COULD EVER CONCEIVABLY WISH TO PARTICIPATE IN REGARDLESS.",
		{
			0,
			0,
			0,
		},
		"\
\
BUT IN THE END. THE JOKE OF IT ALL IS. IT'S JUST ME TELLING MYSELF WHAT TO DO WITH MY PUPPET. AND THEN DOING IT. YOU WILL AGREE THIS IS THE HEIGHT OF CREATIVE SELF INDULGENCE. ",
		{
			0,
			0,
			0,
		},
		"\
\
IN FACT, FOR ME TO EVEN BE MOCKING THE PRACTICE. ALMOST FEELS. INCESTUOUSLY MASTURBATORY. ",
		{
			0,
			0,
			0,
		},
		"\
\
(EVEN THOUGH THAT IS A REDUNDANT PHRASE FOR CHERUBS...)",
	},
	next = {
		6254,
	},
	previous = 6252,
	theme = "A6A6",
}