return {
	title = "MALE: EXERCISE FREEDOM TO LEAVE ROOM.",
	pageId = 6259,
	timestamp = "1371079994",
	flag = {},
	media = {
		"06257",
	},
	content = {
		{
			0,
			0,
			0,
		},
		"THE LUCKY MALE IS OBLIVIOUS TO HIS PRIVILEGE. OF NOT BEING CHAINED TO HIS ROOM, WITH THE HORRIBLE SISTER HE DOESN'T HAVE. THE ADVANTAGE MAKES HIM WAY TOO OVERPOWERED, AND THEREFORE HE IS WHAT SOME REFER TO AS A \"HUMAN MARY SUE\". THIS MAKES HIM LESS SYMPATHETIC, AND GIVES YOU ANOTHER REASON. TO ACTIVELY ROUTE FOR HIS DEATH.",
		{
			0,
			0,
			0,
		},
		"\
\
HE GOES DOWNSTAIRS. AND YOU THINK, AH HA. THIS IS IT. SOMETHING IMPORTANT IS HAPPENING. BUT YOUR OBSERVATION IS ANOTHER BRAINLESS FALLACY. THE THING HAPPENING HERE IS JUST AS POINTLESS AS EVERYTHING ELSE.",
		{
			0,
			0,
			0,
		},
		"\
\
THE LARGER HOMO SAPIEN IS OBVIOUSLY ATTEMPTING TO HELP THE MALE GROW UP AND BECOME *STRONG*. THROUGH A RITE OF PASSAGE INVOLVING SWEETS. POSSIBLY TO HELP THE MALE BECOME A TRICKSTER?",
		{
			0,
			0,
			0,
		},
		"\
\
BUT THE MALE IS STUBBORN AND REFUSES. LIKE AN IDIOT.",
	},
	next = {
		6260,
	},
	previous = 6258,
	theme = "A6A6",
}