return {
	title = "I AM ALMOST CERTAIN CHERUB SHAKESPEARE SAID THAT.",
	pageId = 6262,
	timestamp = "1371080207",
	flag = {},
	media = {
		"06260",
	},
	content = {
		{
			0,
			0,
			0,
		},
		"IN THE INTEREST OF FULL DISCLOSURE THOUGH. WHEN DOING FINE ART. SOMETIMES IT PAYS TO CHEAT. AND FIND THINGS THAT ARE HARD TO DRAW. ON THE INTERNET. WHERE THEY ARE ALREADY THERE FOR YOU.",
		{
			0,
			0,
			0,
		},
		"\
\
THIS CAN SAVE TIME. AND MAKE YOU APPEAR TO BE BETTER AT THINGS. THAN YOU REALLY ARE. ",
		{
			0,
			0,
			0,
		},
		"\
\
TAKE THIS ADVICE TO HEART. IF YOU WANT TO BE AS SUCCESSFUL AS ME. (NOT GOING TO HAPPEN, BTW.)",
	},
	next = {
		6263,
	},
	previous = 6261,
	theme = "A6A6",
}