return {
	title = "ANYWAY, BACK TO THE STORY.",
	pageId = 6263,
	timestamp = "1371080252",
	flag = {},
	media = {
		"06261",
	},
	content = {
		{
			0,
			0,
			0,
		},
		"AFTER AN ENDLESS PARADE OF UNAMUSING AND INCONSEQUENTIAL EVENTS. FINALLY SOMETHING HAPPENS. ",
		{
			0,
			0,
			0,
		},
		"\
\
YOU WILL FIND THIS IS CUSTOMARY FOR THIS TALE. LOTS AND LOTS OF STUPID UNIMPORTANT THINGS HAPPEN. THEN FINALLY OUT OF NOWHERE. A STUPID IMPORTANT THING HAPPENS. ",
		{
			0,
			0,
			0,
		},
		"\
\
A METEOR APPEARS WITHOUT EXPLANATION. IT IS HEADED DIRECTLY FOR THE MALE. THERE IS NOTHING HE CAN DO BUT ACCEPT HIS FATE. LOOK. HE DOES NOT EVEN TRY TO FLEE, BECAUSE HE IS AN IGNORAMUS.",
	},
	next = {
		6264,
	},
	previous = 6262,
	theme = "A6A6",
}