return {
	title = "BUT THESE PORTRAITS ARE NOW A MOOT POINT.",
	pageId = 6862,
	timestamp = "1413620385",
	flag = {},
	media = {
		"06859",
	},
	content = {
		{
			0,
			0,
			0,
		},
		"ALL OF THIS WRETCHED TRASH. GOES IN THE PLACE WHERE IT BELONGS. WHICH IS TO SAY, THE *GARBAGE*. ",
		{
			0,
			0,
			0,
		},
		"\
\
THAT'S WHAT HAPPENS WHEN YOU ARE AN ARTIST. SOMETIMES YOU CHANGE YOUR IDEA PLANS. BECAUSE THEY SUDDENLY SEEM TERRIBLE. DUE TO YOUR ASTRONOMICAL STRIDES IN CREATIVE MASTERY.",
		{
			0,
			0,
			0,
		},
		"\
\
THESE WERE THE PIXEL PUPPETS. OF A LAUGHABLE AMATEUR. THEY ARE BENEATH ME NOW. MUCH LIKE YOU ARE.",
		{
			0,
			0,
			0,
		},
		"\
\
BUT IN SPITE OF ALL OF YOUR BAD SHORTCOMINGS. I WILL LET YOU OBSERVE MY ARTISTIC BREAKTHROUGHS. BECAUSE OF HOW PROUD OF THEM I AM. AND WATCHING PEOPLE BE IMPRESSED AT MY DRAWINGS. EVEN DUMB JERKS. MAKES ME FEEL GREAT ABOUT MYSELF AND MY ACCOMPLISHMENTS.",
	},
	next = {
		6863,
	},
	previous = 6861,
	theme = "A6A6",
}