return {
	title = "BUT HEAR ME OUT!",
	pageId = 6868,
	timestamp = "1413620822",
	flag = {},
	media = {
		"06865",
	},
	content = {
		{
			0,
			0,
			0,
		},
		"THE MANGAS PLAY BY DIFFERENT RULES. YOU'LL AGREE WITH THIS. WHEN YOU HEAR THE FACTS OF MY RATIONALE.",
		{
			0,
			0,
			0,
		},
		"\
\
NATURALLY SUCH MAUDLIN DISPLAYS. OF TOUCHING AND SIMPERING. HAVE NO PLACE. WHERE ONLY COCKSURE, MASCULINE GENTLEMEN ARE PRESENT. ",
		{
			0,
			0,
			0,
		},
		"\
\
HOWEVER. BY THE MAN GAKA'S ILLUSIONRY. HE CHANGES EVERYTHING! WHERE BEFORE OUR MALES WERE COARSE. CHISLED. AND CRUDELY ANGULAR. BUILT FOR PRIME TIME. LIKE A FUCKING GARBAGE TRUCK. PLOWING THROUGH THE WALL. OF AN INDUSTRIAL BEEF MILL. SO CUT. SO *MAXED OUT*. THAT THEY COULD ONLY PROVOKE INSIDE A YOUNG MAN. THOUGHTS OF *RAW POWER*. NEVER DEBAUCHERY!!! ",
		{
			0,
			0,
			0,
		},
		"\
\
UNTIL NOW, THAT IS. BECAUSE OF MANGA. AND ITS INHERENT CAPABILITY TO TRANSFORM ALL THAT IS HARD AND CRUEL. INTO FIGURES OF SUBLIME BEAUTY. I FIND THIS ARTIFICE TO BE. MUCH LIKE THE SIREN SPELL OF THE TRICKSTER. YET, IMPOSSIBLY. EVEN MORE HAUNTING IN ITS ALLURE.",
	},
	next = {
		6869,
	},
	previous = 6867,
	theme = "A6A6",
}