return {
	title = "HERE COMES ANOTHER PRIME O.C. OF MINE, HOT OFF THE PRESS.",
	pageId = 6877,
	timestamp = "1413621411",
	flag = {},
	media = {
		"06874",
	},
	content = {
		{
			0,
			0,
			0,
		},
		"NOT TOO SHABBY, RIGHT? YOU CAN JUST TELL THIS \"LUCKY LADY\" IS BRIMMING WITH CHUTZPAH.  ",
		{
			0,
			0,
			0,
		},
		"\
\
ME THINKS SHE WILL BE A VERY CONTROVERSIAL CHARACTER. WITH EXCESSIVE COMPLICATIONS. AND AMBIGUOUS MORAL STUFF. IN HER PERSONALITY BULLET POINTS. ",
		{
			0,
			0,
			0,
		},
		"\
\
HER TRAITS AND OTHER SUCH CHARACTER THINGS. WILL BE A LOT TO LIST. WHICH IS FINE, BECAUSE IT WILL HELP YOU BELIEVE MY CREATION IS MORE INTERESTING. IN FACT. THIS IS ONE SUCH ADVANTAGE OF DOMINATING ALL KNOWN MANGA AS I HAVE DONE. WHEN YOU'RE THIS GOOD, AND BRILLIANT. YOU DON'T EVEN REALLY NEED TO \"TELL STORIES\" ANYMORE. YOU CAN JUST MAKE SOME CHARACTERS. AND LIST THEIR VARIOUS QUALITIES EXTENSIVELY. AND THAT'S GOOD ENOUGH.",
		{
			0,
			0,
			0,
		},
		"\
\
THE MANY. MANY INTRIGUING PERSONAL FACTS. OF THIS TRUCULENT FEMALE PROVOCATEUR. SHALL BE LISTED EXTENSIVELY.",
	},
	next = {
		6878,
	},
	previous = 6876,
	theme = "A6A6",
}