return {
	title = "SERIOUSLY. CAN I GET A GOD DAMN?",
	pageId = 6882,
	timestamp = "1413621766",
	flag = {},
	media = {
		"06879",
	},
	content = {
		{
			0,
			0,
			0,
		},
		"ASK ANY DECORATED SCHOLAR TO THE SCHOOL OF MANGA, AND HE WILL SAY. BEFORE YOU STANDS THE YAOIEST MOTHERFUCKER WHO EVER LIVED. ALL THINGS ABOUT THIS GORGEOUS BASTARD TELL YOU LOUD AND CLEAR. THIS IS A MAN OF CLASS AND STYLE. ",
		{
			0,
			0,
			0,
		},
		"\
\
HE IS DRESSED TO KILL. (LITERALLY! HAHA, YESSS.) LOOK AT THIS FANCY DAN, STRUTTING HIS STUFF AND DAPPER AS FUCK. YOUR BOY HERE PEACOCKS HARD AT HONIES APLENTY, NEGGING THE BITCHES AND CLOSING THE HOES IN A COAT THAT IS FIT FOR A LORD. LOOK AT THAT GOD DAMN COAT. I DON'T KNOW HOW HE GETS THAT COAT? PROBABLY DUE TO A SHENANIGAN THAT TAKES PLACE LATER. I DOUBT IT MATTERS THAT MUCH. IT LOOKS GREAT THOUGH, AND I LOVE IT.",
	},
	next = {
		6883,
	},
	previous = 6881,
	theme = "A6A6",
}