return {
	title = "BIG MAN: HOLLER FOR YOUR WOMAN.",
	pageId = 6884,
	timestamp = "1413621928",
	flag = {},
	media = {
		"06881",
	},
	content = {
		{
			0,
			0,
			0,
		},
		"HIS WOMAN, THAT ELABORATE TRAMP FROM THE SURFACE OF THE TOME, HUSTLES TO THE SIDE OF HER DEBONAIR HOT SHOT. \"MY'LADY\" HE DOFFS RATIONALLY. THE MAN BRIMS WITH INTELLECTUAL IDEAS SHE WOULDN'T UNDERSTAND. HE KNOWS MANY THINGS, ABOUT THE WORLD, AND BEING STRONG. BUT YET... HE STILL DOESN'T KNOW WHO SHE IS. THE GODDESS OF MANGA, PERHAPS?",
		{
			0,
			0,
			0,
		},
		"\
\
IT IS NO MATTER. SHE MUST BOW DOWN BEFORE HER LORD. AS MUST YOU ALL SOME DAY.",
	},
	next = {
		6885,
	},
	previous = 6883,
	theme = "A6A6",
}