return {
	title = "MY MASTERPIECE!",
	pageId = 7411,
	timestamp = "1428897531",
	flag = {
		"F",
	},
	media = {
		"07408/07408.swf",
	},
	content = {
		{
			0,
			0,
			0,
		},
		"THE FRUITS OF MY ARTISTIC TOILS ARE FINALLY AT HAND. YOU'RE WELCOME IN ADVANCE FOR THE NARRATIVE MAJESTY YOU ARE ABOUT TO WITNESS. IT COST LITERALLY MILLIONS OF CALCOINS TO PRODUCE. AS WELL AS MOST OF MY ATTENTION SPAN FOR ANY FURTHER CREATIVE ENDEAVORS. BUT YOU WILL PROBABLY AGREE, TEARFULLY. THAT IT IS WORTH ALL OF THIS EXPENSE, AND MORE. TO SEE MY TINY ACTORS OF LIVING PUTTY, *DANCE*.",
		{
			0,
			0,
			0,
		},
		"\
\
GET READY. TO GET DAZZLED. AS I FUCKING DESTROY THE TRANSCENDENTAL BOUNDARIES OF \"UNCONVENTIONAL MEDIA\". ",
		{
			0,
			0,
			0,
		},
		"\
\
(THAT JUJU CHEST SHOULDN'T BE MOVING. SORRY. I BUMPED IT.)",
	},
	next = {
		7412,
	},
	previous = 7410,
	theme = "A6A6",
}