return {
	title = "LET US BEGIN.",
	pageId = 7412,
	timestamp = "1428897590",
	flag = {
		"F",
	},
	media = {
		"07409/07409.swf",
	},
	content = {
		{
			0,
			0,
			0,
		},
		"THE TALE MY MASTERPIECE DESCRIBES, IS BASICALLY A SPOILER TO THE ENDING OF THINGS. IT TAKES PLACE IN A FUTURE MOMENT. LONG BEYOND WHEN WE, YOU, OR I HAVE ANY BUSINESS SEEING WHAT HAPPENS. ",
		{
			0,
			0,
			0,
		},
		"\
\
BUT I FOUND OUT AND LEARNED OF THIS SPOILER. I SAW IT ONCE, ON ONE OF MY PLANET'S MANY SCREENS. THE LAND OF \"COLOURS\". AND THE LAND OF \"MAYHEM\". IT KNOWS ALL. AND IT WILL SHOW ANYTHING TO ANY MAN. WHO IS WILLING TO FIND THE RIGHT KEY. AND IT TURNS OUT THAT JUST SUCH A MAN. IS THE MAN THAT IS ME!",
	},
	next = {
		7413,
	},
	previous = 7411,
	theme = "A6A6",
}