return {
	title = "ONE MORE BANNER PIECE OF SWAG IN MY POSSESSION.",
	pageId = 7416,
	timestamp = "1428897835",
	flag = {
		"F",
	},
	media = {
		"07413/07413.swf",
	},
	content = {
		{
			0,
			0,
			0,
		},
		"I'M NOT SURE HOW I COME ABOUT THIS LATER. MUCH LIKE THE CLOCKWORK LASERS, AND PRIMO FASHION JACKET. IT'S A RING, THAT FOUND ITS WAY TO ME SOMEHOW. A GOLDEN RING OF VOID. IT BECOMES MINE ONE DAY. THE MOST BEAUTIFUL THING, I NEVER KNEW I ALWAYS WANTED, YET SOMEHOW, PREEMPTIVELY COVETED. IT LETS ME STAY CLOSE TO THE DARKNESS. TO VANISH, AND APPEAR AGAIN, IN PLACES I HAVE NO BUSINESS FUCKING WITH. FULL OF PLUMP AND MEATY PEOPLE. ALIVE AND LIVING. WHO ONE DAY, WILL PLEAD WITH THE GODS. BEGGING THEM TO CURSE MY NAME.",
	},
	next = {
		7417,
	},
	previous = 7415,
	theme = "A6A6",
}