return {
	title = "SO IN THE BLINK OF AN EYE.",
	pageId = 7425,
	timestamp = "1428979416",
	flag = {
		"F",
	},
	media = {
		"07422/07422.swf",
	},
	content = {
		{
			0,
			0,
			0,
		},
		"I TRAPPED IT BACK IN THE CHEST! AND BANISHED IT AWAY, WHERE NO ONE WOULD EVER FIND IT. DEEP IN THE BOWELS OF THE FURTHEST RING. USING MY RING-BASED COMMUNION WITH THE VOID. POOF!!!!!!!!!!! GOOD LUCK DIGGING THAT ONE UP, HATERS. IT IS *NEVER GOING TO HAPPEN*.",
		{
			0,
			0,
			0,
		},
		"\
\
WITH THE FIRST FOUR BANISHED, THE TEAM OF HEROES WAS CUT IN HALF, TO BE MUCH EASIER FOR ME TO DEVASTATE. A SMUTTY SWORDSMAN, AN UNDERPANTS WIMP, AND TWO FLIPPANT BIMBOS? I WOULD CALL IT A CAKE WALK. BUT WHEN YOU ARE THIS COCKY AND BRASH. YOU DON'T WALK. YOU STRUT. NO MATTER WHAT KIND OF DESSERT YOU FIND UNDER YOUR FEET.",
	},
	next = {
		7426,
	},
	previous = 7424,
	theme = "A6A6",
}