return {
	title = "I'M RUINING THEM, REALLY.",
	pageId = 7430,
	timestamp = "1428980398",
	flag = {
		"F",
	},
	media = {
		"07427/07427.swf",
	},
	content = {
		{
			0,
			0,
			0,
		},
		"IT'S NOT A CONTEST. THEY ARE A BUNCH OF PITIFUL EMOTION CHILDREN, AND I AM A PREMIER, INVINCIBLE TITAN OF ROUGHHOUSE BRUTALITY. IT'S TOO EASY. SPEEDO BOY IS DOWN FOR THE COUNT, BECAUSE I SLAPPED HIM GINGERLY. THE MASKED FLOOZY IS LOOKING A BIT... WOOZY (HA HA.) THE CAKE MAID TOOK ONE DRUB TOO MANY AND HAS TO LIE DOWN FOR AN OVERWEIGHT NAP. THIS LEAVES ME, MANO & MANO, AGAINST THE ANIME PRINCE AND HIS NONSENSE TROUSERS.",
	},
	next = {
		7431,
	},
	previous = 7429,
	theme = "A6A6",
}