return {
	title = "IT WAS A PRETTY GOOD FIGHT BETWEEN US.",
	pageId = 7431,
	timestamp = "1428980544",
	flag = {
		"F",
	},
	media = {
		"07428/07428.swf",
	},
	content = {
		{
			0,
			0,
			0,
		},
		"BECAUSE HE'S STRONG, AND I ADMIRE THAT. WHY SHOULDN'T I LET A BATTLE HAPPEN FOR LONGER, WHEN TWO TOUGH DUDES ARE INVOLVED, STRUTTING THEIR STUFF. BUT IN THE END, HIS SHARP GLASSES AND SWORD MACHISMO WEREN'T ENOUGH. I GOT THE SUPREME DROP ON HIS POWERFUL BODY WITH MY WRESTLING MOVES.",
	},
	next = {
		7432,
	},
	previous = 7430,
	theme = "A6A6",
}