return {
	title = "THE SWEATY MUSCULAR GHOST APPEARS OUT OF NOWHERE.",
	pageId = 7441,
	timestamp = "1429067989",
	flag = {
		"F",
	},
	media = {
		"07438/07438.swf",
	},
	content = {
		{
			0,
			0,
			0,
		},
		"I HAVE NO IDEA WHO HE IS. OR WHERE HE CAME FROM. JUDGING FROM THE FACE OF THE GUYS, THEY DON'T EITHER. NOBODY SEES THIS COMING. IT IS A TOTAL AMBUSCADE, AND MY SKELETON JAW IS DROPPED AS SHIT. HE PINS ME IN PLACE WITH HIS RIPPED MUSCLES, AND I'M COMPLETELY IMMOBILIZED. PARTLY BECAUSE OF THE *STRENGTH*, BUT ALSO DUE TO MY AWE AND ADMIRATION. I JUST CAN'T MOVE.",
	},
	next = {
		7442,
	},
	previous = 7440,
	theme = "A6A6",
}