return {
	title = "I THINK HE THOUGHT HE COULD DESTROY MY SOUL.",
	pageId = 7443,
	timestamp = "1429068159",
	flag = {
		"F",
	},
	media = {
		"07440/07440.swf",
	},
	content = {
		{
			0,
			0,
			0,
		},
		"BUT HE BIT OFF MORE THAN HIS FLESHY SKULL COULD CHEW. SO HE USED HIS \"IRONY\" AGAIN. AND STUCK MY SOUL IN HIS JUJU. EXACTLY THE WAY. I STUCK HIS BUDDIES IN MY JUJU. THE ONE I GOT FROM YODELBOOGER. IT'S LIKE POETIC JUSTICE I GUESS. EXCEPT PUPPETRY, INSTEAD OF POETRY. SO PUPPETIC JUSTICE. OH YES. I LIKE THAT. ",
		{
			0,
			0,
			0,
		},
		"\
\
THE MUSCLE GHOST CAME ALONG FOR THE RIDE. AND I GUESS HIS SOUL GOT TRAPPED IN THERE TOO? I HAVE NO IDEA WHAT THAT MEANS. HONESTLY IT IS DISTURBING AS HELL. AND I'D PREFER NOT TO DWELL ON ITS GREATER RAMIFICATIONS TO MY LONG TERM EXISTENCE. MAYBE IT'S GOOD? OR MAYBE IT'S DUMB. MAYBE IT'S. GOOD AND DUMB. OR SMART AND BAD. THERE ARE SO MANY WORDS THINGS CAN BE WHEN YOU'RE CONFUSED.",
	},
	next = {
		7444,
	},
	previous = 7442,
	theme = "A6A6",
}