return {
	title = "AT THIS POINT.",
	pageId = 7444,
	timestamp = "1429068231",
	flag = {
		"F",
	},
	media = {
		"07441/07441.swf",
	},
	content = {
		{
			0,
			0,
			0,
		},
		"HIS BELOVED JUJU IS NO LONGER A HOLLOW VESSEL. IT IS VERY MUCH CROWDED IN THERE, CHOCK FULL OF SOULS, BELONGING TO HARDCORE BRAWLING BRUTES. AND HE KNOWS IT. HIS PUPPET IS NOW A PROBLEM TO DO AWAY WITH, JUST LIKE MY JUJU WAS. SO THEY DO THE SAME BASIC THING. THEY GET THEIR DRUNKARD SORCERESS OF VOID TO BANISH THE PUPPET ONCE AND FOR ALL, INTO THE DARKNESS. NEVER TO BE FOUND AGAIN BY PROBING HANDS OF MEAT.",
	},
	next = {
		7445,
	},
	previous = 7443,
	theme = "A6A6",
}