return {
	title = "YES, NEVER TO BE FOUND.",
	pageId = 7445,
	timestamp = "1429068328",
	flag = {
		"F",
	},
	media = {
		"07442/07442.swf",
	},
	content = {
		{
			0,
			0,
			0,
		},
		"BUT NOT NEVER TO RESURFACE. OH NO. ",
		{
			0,
			0,
			0,
		},
		"\
\
YOU SEE, MY SOUL IS A TENACIOUS ONE. I KNOW THIS FACT FIRST HAND, BECAUSE IT HAS BEEN INSIDE MY BRAIN ALL MY LIFE! IT'S A REAL MOTHER FUCKER, I'LL TELL YOU THAT MUCH. THE PUPPET'S ESSENCE WILL FLOP AND FLUTTER THROUGH THE SHADOWS FOR ETERNITY. SURFACING IN THE NIGHTMARES OF THE UNSUSPECTING. WEASELING ITS WAY INTO THE HEARTS OF YUCKY SHITTY CHILDREN. AND WHEN ITS INFILTRATION IN THAT UNIVERSE HAS TAKEN HOLD, THE SEED WILL HAVE BEEN PLANTED. AND IT WILL PAVE THE WAY FOR MY EMERGENCE, TO WREAK MY BADNESS. FROM UNIVERSE. TO UNIVERSE. TO UNIVERSE. EACH ONE WILL FALL. AND EACH TIME I WILL GET STRONGER. AND OLDER. AND BIGGER. AND BUFFER! OHHHHHHHHHHH YES. ",
		{
			0,
			0,
			0,
		},
		"\
\
IT WILL BE TIME.",
	},
	next = {
		7446,
	},
	previous = 7444,
	theme = "A6A6",
}