return {
	title = "John: Collect grist, examine safe.",
	timestamp = "1251346046",
	flag = {},
	media = {
		"00542",
	},
	content = {
		{
			0,
			0,
			0,
		},
		"You swoop up the bountiful supply of\
",
		{
			0,
			0,
			0,
		},
		"grist generated by your co-player's\
",
		{
			0,
			0,
			0,
		},
		"recent exploits. From now on it will\
",
		{
			0,
			0,
			0,
		},
		"probably go without saying that you'll\
",
		{
			0,
			0,
			0,
		},
		"nab any grist lying around without\
",
		{
			0,
			0,
			0,
		},
		"making a big fuss over it.\
",
		{
			0,
			0,
			0,
		},
		"\
",
		{
			0,
			0,
			0,
		},
		"\
",
		{
			0,
			0,
			0,
		},
		"You check out the busted SAFE, which\
",
		{
			0,
			0,
			0,
		},
		"has made a noble sacrifice in battle.\
",
		{
			0,
			0,
			0,
		},
		"Some of your father's odds and ends\
",
		{
			0,
			0,
			0,
		},
		"have spilled out, including some old\
",
		{
			0,
			0,
			0,
		},
		"NEWSPAPER CLIPPINGS, and two rather\
",
		{
			0,
			0,
			0,
		},
		"hefty TOMES. It's a fair bet that\
",
		{
			0,
			0,
			0,
		},
		"these books comprised at least half\
",
		{
			0,
			0,
			0,
		},
		"the weight of the safe.\
",
	},
	next = {
		543,
	},
	previous = 541,
	log_title = "",
	log = {},
	page_id = 542,
	title_len = 34,
}