return {
	title = "HERE IS WHAT REALLY MATTERS.",
	pageId = 6245,
	timestamp = "1371078804",
	flag = {
		"R4",
	},
	media = {
		"06242_retcon",
	},
	content = {
		{
			0,
			0,
			0,
		},
		"A YOUNG MALE CHERUB HAS ACHIEVED TOTAL DOMINATION OVER HIS QUEST. THUS UNLOCKING HIS MAGIC MYSTERY PLANET. AND THEREFORE. GAINING SUPREME MASTERY OVER ALL EVENTS IN REALITY. CANONICAL OR OTHERWISE.",
		{
			0,
			0,
			0,
		},
		"\
\
HE BECAME A GOD TIER OBVIOUSLY. IT WAS EASY, INVOLVING A TRIVIAL ACT OF SELF SUICIDE. IT WAS NOT A VERY BIG DEAL AT ALL. THAT'S WHAT HAPPENS WHEN YOU'RE THE BEST. YOU BECOME THE BEST THING QUITE CASUALLY. AND OFF SCREEN. LIKE IT'S NOT EVEN THAT IMPORTANT.",
	},
	next = {
		6246,
	},
	previous = 6244,
	theme = "A6A6",
}