return {
	title = "MALE: BOGGLE VACANTLY AT THESE SHENANIGANS.",
	pageId = 6261,
	timestamp = "1371080149",
	flag = {},
	media = {
		"06259",
	},
	content = {
		{
			0,
			0,
			0,
		},
		"IT BEGINS TO DAWN ON YOU. THAT EVERYTHING YOU JUST DID. MAY HAVE BEEN A COLOSSAL WASTE OF TIME.",
		{
			0,
			0,
			0,
		},
		"\
\
IT ALSO BEGINS TO DAWN ON YOU. THAT I WAS THE ONE ALL ALONG. WHO ILLUSTRATED THIS FANTASTIC CARTOON RECTANGLE. WHICH YOU REMEMBER THAT YOU SAW BEFORE SOMEWHERE. AND YOU NOW FIND THIS REVELATION TO BE. ALMOST AS RETROACTIVELY PLAUSIBLE. AS IT IS MIND BLOWING.",
		{
			0,
			0,
			0,
		},
		"\
\
IT BRINGS TO MIND A FAMOUS QUOTE. FROM A CELEBRATED POET OF YORE. THAT I THINK GOES LIKE THIS.",
		{
			0,
			0,
			0,
		},
		"\
\
\"WELL SHIT. THAT'S A HELL OF A MYSTERY. NO ONE THOUGHT WAS A MYSTERY. AND DIDN'T EVEN REALLY NEED SOLVING. BUT DAMN IF IT DIDN'T JUST GET SOLVED. SO NICE WORK.\"",
		{
			0,
			0,
			0,
		},
		"\
\
- CHERUB SHAKESPEARE, PROBABLY.",
	},
	next = {
		6262,
	},
	previous = 6260,
	theme = "A6A6",
}