return {
	title = "CONFIRM THE KILL.",
	pageId = 6265,
	timestamp = "1371080587",
	flag = {},
	media = {
		"06263",
	},
	content = {
		{
			0,
			0,
			0,
		},
		"YOU (I) PRODUCE PHOTOGRAPHIC EVIDENCE OF THE SLAUGHTERED MALE BODY. HE IS INDEED DEAD. AND WILL STAY DEAD FOR THE WHOLE STORY. ONLY HIS GHOST WILL SHOW UP NOW AND THEN. IN A BLURRY FLASH OF LIGHT. TO HAUNT ME PERIODICALLY THROUGHOUT HISTORY. (BUT I WILL SAY MORE ABOUT THAT LATER.)",
		{
			0,
			0,
			0,
		},
		"\
\
YOU (YOU) THINK THE ABOVE GRAPHIC LOOKS FAMILIAR. YOU THINK YOU HAVE SEEN THIS GREAT DRAWING BEFORE, IN A DIFFERENT CONTEXT. YOU SEE. THIS IS WHAT MASTER STORY TELLERS REFER TO AS A \"VISUAL CALLBACK\". TRULY EXCEPTIONAL PROFESSIONALS OFTEN WILL TAKE AN OLD DRAWING THEY DID. THAT SHOWS A SIMILAR SITUATION. AND DO A COUPLE OF HALF ASSED THINGS. LIKE CHANGE THE COLORS. TO MAKE IT SLIGHTLY DIFFERENT. ",
		{
			0,
			0,
			0,
		},
		"\
\
YOU (STILL YOU) OBSERVE THAT THIS INGENIOUS FEAT OF LAZINESS. MAKES THE REPEATED THINGS SEEM MORE PROFOUND AND MEANINGFUL THAN THEY ARE. FOR REASONS YOU DON'T UNDERSTAND. BECAUSE THEY DON'T EXIST. THIS IS A TRADE SECRET AMONG SKILLED ARTISANS SUCH AS I. ",
		{
			0,
			0,
			0,
		},
		"\
\
PLEASE TRY TO KEEP THIS ON THE DOWN LOW. AND NOT TELL ANYBODY. IT CAN BE OUR SECRET. THEY DON'T EVEN NEED TO KNOW!",
	},
	next = {
		6266,
	},
	previous = 6264,
	theme = "A6A6",
}