return {
	title = "THE END. OF ACT 1.",
	pageId = 6266,
	timestamp = "1371080898",
	flag = {},
	media = {
		"06264",
	},
	content = {
		{
			0,
			0,
			0,
		},
		"THIS CONCLUDES THE FIRST THING OF THE STORY. WHICH IS CALLED AN \"ACT\". ",
		{
			0,
			0,
			0,
		},
		"\
\
THERE ARE A LOT OF THESE. AND THEY ONLY GET LONGER. AND THEN BEGIN TO SPLIT? INTO ACT ACTS. AND ACT ACT ACTS. TRUST ME. THE STRUCTURE RAPIDLY DETERIORATES INTO UTTER NONSENSE. OR AT LEAST IT WOULD. IF IT HAD NOT ALREADY BEGUN. AS SUCH A REEKING PILE OF SHIT OUT OF THE BOX.",
		{
			0,
			0,
			0,
		},
		"\
\
BUT PLEASE DO NOT WORRY. I WILL BE THERE TO GUIDE YOU. THROUGH EVERY MIND NUMBING TWIST AND TURN. WHILE PRODDING THE MATERIAL WITH MY KEEN WIT. AND SATIRICIZE THE HELL OUT OF EVERYTHING. TO HOLD THE RESPONSIBLE PARTIES FULLY ACCOUNTABLE FOR THESE CRIMES. WHILE MAXIMALLY VALIDATING MY ANGRINESS ABOUT IT.",
		{
			0,
			0,
			0,
		},
		"\
\
MAYBE YOU THOUGHT YOU WERE GOING TO SEE SOME OTHER STUFF. LIKE WHAT HAPPENS TO ALL THESE IDIOTS \"NEXT\"? THE ANSWER IS OBVIOUSLY WHO CARES. THIS IS GOING TO BE SO MUCH BETTER. EITHER WAY, YOU HAVE NO CHOICE. I AM IN TOTAL CHARGE HERE NOW. ",
		{
			0,
			0,
			0,
		},
		"\
\
I BELIEVE AT THIS POINT. ANOTHER ONE OF MY VILLAINOUS, FULL THROATED LAUGHS WILL BE IN ORDER.",
	},
	next = {
		6267,
	},
	previous = 6265,
	theme = "A6A6",
}