return {
	title = "==>",
	pageId = 6270,
	timestamp = "1371081456",
	flag = {},
	media = {
		"06268",
	},
	content = {
		{
			0,
			0,
			0,
		},
		"WHO IS THIS EXTRAVAGANT BITCH.",
		{
			0,
			0,
			0,
		},
		"\
\
IS SHE PARTLY A ROBOT. SORT OF LIKE ME. OH, SHE SEEMS TO BE AN ARTIST TOO. ALSO LIKE ME.",
		{
			0,
			0,
			0,
		},
		"\
\
DID SHE DRAW HERSELF?? I DON'T SEE HOW THAT'S POSSIBLE. CONSIDERING SHE IS FICTIONAL. AS WELL AS A GIRL. SOME OTHER VERY SKILLED DRAFTSMAN MUST HAVE DRAWN IT. BUT HOW DID HE MAKE IT LOOK LIKE SHE IS COMING OUT OF THE PAPER? WHEN I TURN THE BOOK. THE IMAGE STAYS FLAT. AND THE ILLUSION IS EXPOSED. I WONDER IF THE SORCERER OF THIS SO CALLED \"MANGA\" REVEALS THE NATURE OF HIS WIZARDRY INSIDE THE TOME.",
		{
			0,
			0,
			0,
		},
		"\
\
WHY IS THE FRIENDLY BITCH LOOKING AT ME LIKE THAT. WITH THE LARGE GLASSY EYES, AND SHINY FACE. IT'S MAKING ME HAVE WEIRD FEELINGS IN MY BODY.",
		{
			0,
			0,
			0,
		},
		"\
\
I HAVE TO PUT THIS DOWN.",
	},
	next = {
		6271,
	},
	previous = 6269,
	theme = "A6A6",
}