return {
	title = "BE A DIFFERENT MALE.",
	pageId = 6476,
	timestamp = "1377739361",
	flag = {},
	media = {
		"06473",
	},
	content = {
		{
			0,
			0,
			0,
		},
		"THE LAST TIME THAT THINGS HAPPENED. THE MALE STORY HERO BLEW UP. SO FORTUNATELY. WE WON'T SEE HIM EVER AGAIN. ",
		{
			0,
			0,
			0,
		},
		"\
\
THAT MEANS WE NEED TO BE A NEW MALE TO LEAD THE STORY. HERE HE IS. WITH HIS DUMB BLACK GLASSES AND EVERYTHING. ",
		{
			0,
			0,
			0,
		},
		"\
\
HERE TO ONWARD. I WILL REFER TO THIS MALE AS. THE ALPHA MALE.",
		{
			0,
			0,
			0,
		},
		"\
\
THE ALPHA MALE IS LESS BAD THAN THE ORIGINAL MALE. HE IS NOT AS ANNOYING. AND HAS NO TENDENCY TO RANDOMLY APPEAR AND BOTHER PEOPLE. HE ALSO LIKES COOL SWORDS. AND \"IRONY\" I GUESS. AND LIKE MYSELF. HE HAS CULTIVATED A TASTE FOR FINE ART. HENCE, HE WILL BE MY MALE OF CHOICE ON THIS ADVENTURE.",
		{
			0,
			0,
			0,
		},
		"\
\
BUT I WILL ADMIT. THERE IS ONE REASON ABOVE OTHERS. WHY I HAVE DECIDED TO FAVOR THE ALPHA MALE.",
	},
	next = {
		6477,
	},
	previous = 6475,
	theme = "A6A6",
}