return {
	title = "ALPHA MALE: CALL FOR BACKUP.",
	pageId = 6478,
	timestamp = "1377739530",
	flag = {},
	media = {
		"06475_1",
		"06475_2",
	},
	content = {
		{
			0,
			0,
			0,
		},
		"NORMALLY. HERE'S WHAT WOULD HAPPEN.",
		{
			0,
			0,
			0,
		},
		"\
\
HE WOULD TALK INTO HIS GLASSES OR SOMETHING. LIKE A PITIFUL LOSER. IN DOING SO HE WOULD SUMMON BELOW HIS RECTANGLE. WHAT IS KNOWN AS. A PESTERLOG.",
		{
			0,
			0,
			0,
		},
		"\
\
IT IS NEVER ADVISABLE TO OPEN A PESTERLOG. YOU SEE. THE BUTTON IS A TRAP. WHICH WHEN SPRUNG. RELEASES WORDS UPON WORDS. WHICH ONLY SERVE TO REMIND YOU. OF YOUR INTENSE DISLIKE FOR THE PEOPLE SAYING THE THINGS. AS WELL AS. HOW LITTLE REGARD THE AUTHOR HAS. FOR YOUR VALUABLE TIME.",
		{
			0,
			0,
			0,
		},
		"\
\
AS SUCH. THERE WILL BE NO WORDS DESCRIBED IN MY TALE. ONLY ACTION!",
	},
	next = {
		6479,
	},
	previous = 6477,
	theme = "A6A6",
}