return {
	title = "I DON'T RECALL WHAT HIS LAND WAS THOUGH.",
	pageId = 6494,
	timestamp = "1377892125",
	flag = {},
	media = {
		"06491",
	},
	content = {
		{
			0,
			0,
			0,
		},
		"SOMETHING WITH LAVA I THINK? I DON'T REALLY CARE. I WILL JUST MAKE UP MY OWN. IT WILL BE A GREAT OPPORTUNITY. TO FLEX MY POWERFUL *WORLD BUILDING* MUSCLES FOR YOU TO BE DAZZLED BY.",
		{
			0,
			0,
			0,
		},
		"\
\
YOU SEE. WHEN CRAFTING A STRONG AND COMPELLING NARRATIVE. I THINK IT'S IMPORTANT FOR AN ACCOMPLISHED ARTIST. TO GIVE HIMSELF THE LATITUDE TO DO WHATEVER HE WANTS. AND TO FUCK AROUND AS MUCH AS CHERUBICALLY POSSIBLE. AND THE SIZE OF THAT LATITUDE SHOULD BE. LITERALLY AS BIG. AS THE WHOLE FUCKING STORY.",
		{
			0,
			0,
			0,
		},
		"\
\
AS SUCH. USING KNOWLEDGE ACCRUED FROM MY TOMES OF ARTISAN KNOWLEDGE. I WILL CHANGE MY \"ART STYLE\". TO DEMONSTRATE MY VERSATILITY. AND MAKE YOU BE IMPRESSED.",
		{
			0,
			0,
			0,
		},
		"\
\
HOWEVER. THE MANGAS ARE CLEARLY TOO ADVANCED FOR NOW. AFTER I LEVEL UP IN FINE ART. MAYBE. BUT NOT NOW.",
		{
			0,
			0,
			0,
		},
		"\
\
SO FOR THE TIME BEING. AND TO GET MORE PRACTICE. ALL OF MY WORLD ASSETS. WILL BE RESPECTFULLY PLAGIARIZED FROM THE DISTINGUISHED MR. EMBERLY.",
	},
	next = {
		6495,
	},
	previous = 6493,
	theme = "A6A6",
}