return {
	title = "HOW DID I DO SUCH A SENSATIONAL FEAT? YOU ASK.",
	pageId = 6856,
	timestamp = "1413619989",
	flag = {},
	media = {
		"06853_1",
		"06853_2",
		"06853_3",
	},
	content = {
		{
			0,
			0,
			0,
		},
		"THE MYSTERY TO SUCCESS. LAY HIDDEN AMIDST THE BYZANTINE MANGAS. ALL ALONG.",
		{
			0,
			0,
			0,
		},
		"\
\
THESE OCCULT WIZARDRIES OF THE BRUSH. PURLOINED FROM COOL SCROLLS OF WISE MEN FROM THE EARTHLING EAST. HAVE BEEN GATHERED FOR MY STUDIOUS PERUSAL INSIDE A SEDUCTIVE TOME. EMBLAZONED WITH A FRIVOLOUS TART.",
		{
			0,
			0,
			0,
		},
		"\
\
HOWEVER, MASTERING EACH SLY GAMBIT OF THE TRADE. IS NO EASY TASK.",
		{
			0,
			0,
			0,
		},
		"\
\
AND YET EASILY MASTERING THEM. WITH GREAT DIFFICULTY. IS EXACTLY WHAT I DID!",
	},
	next = {
		6857,
	},
	previous = 6855,
	theme = "A6A6",
}