return {
	title = "OH MY. WHAT HAVE WE HERE?",
	pageId = 6866,
	timestamp = "1413620667",
	flag = {},
	media = {
		"06863",
	},
	content = {
		{
			0,
			0,
			0,
		},
		"DON'T LOOK NOW. BUT ANOTHER BASHFUL BISHIE APPROACHES THE STAGE.",
		{
			0,
			0,
			0,
		},
		"\
\
IT'S OUR TROLL MALE. KRAB GUY. QUITE A TEMPER, THIS ONE! HE BELLOWS HIMSELF HOARSE DAILY. AT OUR SMART TALKING. GIVE NO FUCK. ALPHA MALE.",
		{
			0,
			0,
			0,
		},
		"\
\
THESE MOE BROS PUT THE PAL, IN PALPABLE CHEMISTRY. THE KIND OF WHICH IS BAD, AS WELL AS EROTIC. THE SAGE ELDERS OF MANGA DESCRIBE THE QUADRANT THEY OCCUPY, AS I QUOTE \"TSUNDERE\". IT IS A TEMPESTUOUS LIAISON OF MUTUAL GRIEVANCE. AND YET, DEEP DOWN. THEY KNOW IN EACH OTHER'S HEART THAT THEY ARE SOLID DUDES.",
	},
	next = {
		6867,
	},
	previous = 6865,
	theme = "A6A6",
}