return {
	title = "I MUST SAY. THE ARTISTIC PLOY. IS INGENIOUS.",
	pageId = 6869,
	timestamp = "1413620952",
	flag = {},
	media = {
		"06866",
	},
	content = {
		{
			0,
			0,
			0,
		},
		"IT OPENS UP SO MANY POSSIBILITIES. TO THE FIEND OF INDECENT SMUT. WHERE BEFORE, IT WAS ALL BUT IMPOSSIBLE. TO RENDER TRULY *****SENTIMENTAL***** IMAGERY, WITHOUT RESORTING TO BABES AND BIMBOS GALORE. DUE TO THE UTTERLY UNACCEPTABLE HAPPENSTANCE WHERE IN MACHO GUYS ARE PHYSICALLY POIGNANT WITH EACH OTHER. WHICH TO REASONABLE MEN IS THE MOST UNWELCOME PERSUASION OF LECHERY. OR THAT IS, IT WAS...",
		{
			0,
			0,
			0,
		},
		"\
\
UNTIL NOW!",
		{
			0,
			0,
			0,
		},
		"\
\
LOOK HOW SMART THIS HOAX IS. THANKS TO MANGA. SEE. THROUGH THE ELEGANCE OF BEAUTY AND FINESSE. IT SOFTENS THE UNCOUTH MALE EXTERIOR. BEVELING THE ANGLES OF PURE MUSCLE. TAMING HIS INCREDIBLE ANGRINESS. AND BY THE FLUSHING OF CHEEKS. THE DEWING OF BROW. THE GLASSING OF EYES. ONE BRINGS OUT OF ANY BRUTE, HIS TRUE INNER BISHIE. WHICH ACTUALLY IS MANGANESE. FOR A BEAUTIFUL FUCKING DUDE.",
		{
			0,
			0,
			0,
		},
		"\
\
IF YOU'RE CONFUSED, BASICALLY THE IDEA IS. YOU PRETEND THEM TO LOOK MORE LIKE GIRLS. TO MAKE IT LESS WEIRD FOR EVERYBODY WHEN THEY DECIDE TO TOUCH EACH OTHER.",
		{
			0,
			0,
			0,
		},
		"\
\
I MEAN. IT IS REPULSIVE TO WITNESS. DO NOT GET ME WRONG. ",
		{
			0,
			0,
			0,
		},
		"\
\
BUT YET, IT REMAINS...",
	},
	next = {
		6870,
	},
	previous = 6868,
	theme = "A6A6",
}