return {
	title = "GODDESS OF MANGA: BOW DOWN.",
	pageId = 6885,
	timestamp = "1413622059",
	flag = {},
	media = {
		"06882",
	},
	content = {
		{
			0,
			0,
			0,
		},
		"SHE BOWS BEFORE YOU SUBMISSIVELY IN A SUBSERVIENT MANNER. EVERYTHING IS CORRECT ABOUT THE SITUATION. YOU THINK SHE'S REALLY ATTRACTIVE, AND IT MAKES YOU FEEL WEIRD PHYSICALLY. AND YET, UNLIKE YOUR SISTER, SHE KNOWS HER PLACE. AND HAS NO OPINIONS OR WORDS TO REMARK ABOUT.",
		{
			0,
			0,
			0,
		},
		"\
\
I MEAN...",
		{
			0,
			0,
			0,
		},
		"\
\
NOT TO IMPLY THAT ANY OTHER ASPECT OF HER IS LIKE YOUR SISTER. LIKE BEING ATTRACTIVE. WOW. WHAT? READ INTO STUFF MUCH? YOU DECIDE YOU HAVE TOO MUCH TIME ON YOUR HANDS. YOU STOP THINKING ABOUT THIS TOPIC STARTING AS OF IMMEDIATELY.",
		{
			0,
			0,
			0,
		},
		"\
\
ALL IS WELL AND IDEAL AGAIN, WITHOUT YOU BLURTING OUT UNNECESSARY SEXY SCANDALS. IT IS ALMOST A BIT. *TOO* IDEAL, YOU THINK.",
		{
			0,
			0,
			0,
		},
		"\
\
\"HMM.\"",
	},
	next = {
		6886,
	},
	previous = 6884,
	theme = "A6A6",
}