return {
	title = "THE SAVVY CASH GIVER WILL ALSO BE PLEASED TO KNOW.",
	pageId = 6941,
	timestamp = "1414893090",
	flag = {},
	media = {
		"06938",
	},
	content = {
		{
			0,
			0,
			0,
		},
		"THAT I AM GRACIOUSLY ACCEPTING \"CAL COINS\". THE BLEEDING EDGE OF MODERN IMAGINARY CURRENCY. WHICH I RECENTLY MADE UP WITH MY COMPUTER. AND CAN CONFIDENTLY CLAIM. TO LARGELY UNDERSTAND.",
	},
	next = {
		6942,
	},
	previous = 6940,
	theme = "A6A6",
}