return {
	title = "SO I WILL SHOW YOU WHAT I SAW.",
	pageId = 7413,
	timestamp = "1428897641",
	flag = {
		"F",
	},
	media = {
		"07410/07410.swf",
	},
	content = {
		{
			0,
			0,
			0,
		},
		"NOT WITH THE CRUDE 2 DIMENSIONAL SHAPES FROM MY COMPUTER PENCIL. BUT WITH THE LAVISH 2+ DIMENSIONAL FORMS OF MY GROUND BREAKING CLAY PUPPETS. BEHOLD AS I INNOVATE OBJECTS OF ARTISTIC EXPRESSION, WHICH YOU TRASHY FUCK MUNCHES NEVER THOUGHT TO PIONEER BEFORE IN A MILLION YEARS. HERE'S A SHOT OF ME BOWING IN ADVANCE FOR BEING GREAT!",
	},
	next = {
		7414,
	},
	previous = 7412,
	theme = "A6A6",
}