return {
	title = "AH YES. MOVIE MAGIC AT ITS BEST.",
	pageId = 7414,
	timestamp = "1428897710",
	flag = {
		"F",
	},
	media = {
		"07411/07411.swf",
	},
	content = {
		{
			0,
			0,
			0,
		},
		"I WILL TELL YOU WHAT I SAW IN THE SCREEN. BELIEVE ME WHEN I SAY, THAT IT HAPPENED PRECISELY AS I SHOW YOU HERE. SHOT FOR SHOT. ",
		{
			0,
			0,
			0,
		},
		"\
\
THIS TAKES PLACE AFTER I GET THE MAGIC RAINBOW EYES. AND YET, STILL BEFORE I AM HUGE AND WEAR A DAPPER TRENCH COAT FOR WINNERS. BUT AS YOU CAN SEE. AT THIS POINT, IN MY RISE TO DOMINANT INVINCIBILITY. I'M FEELING PRETTY CHUFFED ABOUT MYSELF. MY POWER IS SICK, AND MY SPECIAL EYE BALLS ARE GNARLY AS CAN BE. I WOULD TELL YOU I CAN HARDLY WAIT TO BE THIS COOL, BUT AS YOU KNOW. I AM A MAN OF PATIENCE AND APLOMB.",
	},
	next = {
		7415,
	},
	previous = 7413,
	theme = "A6A6",
}