return {
	title = "ALSO, LOOK CLOSELY.",
	pageId = 7415,
	timestamp = "1428897773",
	flag = {
		"F",
	},
	media = {
		"07412/07412.swf",
	},
	content = {
		{
			0,
			0,
			0,
		},
		"I'VE GOT MY JUJU CHEST THERE. WHICH I WILL WIN AS SOME CHOICE BOOTY, FROM VICTORIOUSLY SLAUGHTERING MY DENIZEN. KING YALDOBOB. INSIDE IS A MIGHTY WEAPON. WHICH WILL COME INTO PLAY A LITTLE LATER. IN MY THEATER OF WOBBLING PUPPET DRAMA. IT'S LIKE THEY SAY ABOUT THE THEATER. IF YOU SEE A JUJU IN ACT ONE. THEN THE JUJU WILL PROBABLY BE USED RIGHT AWAY IN ACT ONE. TO MAKE EVERYTHING MORE EXCITING, AS SOON AS POSSIBLE. ",
		{
			0,
			0,
			0,
		},
		"\
\
ALSO, WHICH I SHOULD MENTION...",
	},
	next = {
		7416,
	},
	previous = 7414,
	theme = "A6A6",
}