return {
	title = "THEY ARE ALL FRISKY, AND READY TO FIGHT.",
	pageId = 7420,
	timestamp = "1428898052",
	flag = {
		"F",
	},
	media = {
		"07417/07417.swf",
	},
	content = {
		{
			0,
			0,
			0,
		},
		"I CAN TELL THEY ARE PSYCHED ABOUT THIS. LIKE THEY HAVE BEEN PLANNING IT, AND BIDING THEIR TIME, AND NOW THEY THINK THEY ARE STRONG ENOUGH TO OVERTAKE ME, IF ONLY BECAUSE OF THE SURPRISINGNESS OF THEIR AMBUSH. AND MAYBE THEY ARE EVEN RIGHT. MAYBE THEY COULD BEAT ME. THEY HAVE A LOT OF FIGHTING LEVELS AND MAGIC BOONS NOW, JUST LIKE ME. BUT SEE. I DON'T EVEN GIVE THEM THE CHANCE.",
	},
	next = {
		7421,
	},
	previous = 7419,
	theme = "A6A6",
}