return {
	title = "AND RULES AND STUFF.",
	pageId = 7422,
	timestamp = "1428979237",
	flag = {
		"F",
	},
	media = {
		"07419/07419.swf",
	},
	content = {
		{
			0,
			0,
			0,
		},
		"ALL JUJUS HAVE RULES. THE COOLER THE JUJU. THE TRICKIER THE RULES. FOR ONE THING. THIS WEAPON COULD ONLY BE USED AGAINST FOUR GUYS AT A TIME. BECAUSE ITS SHAPE HAS. LIKE FOUR SLOTS OR SOMETHING. SO I CHOOSE MY TARGETS CAREFULLY. ",
		{
			0,
			0,
			0,
		},
		"\
\
I SELECT THE FOUR OF THESE JOKERS, WHO I DEEM THE GREATEST THREAT TO ME. THE BLUE PHILISTINE WITH THE BELLIGERENT FISTS, OF COURSE. SO HE CAN'T OWN ME AGAIN, WITH HURTFUL INSULTS TO MY ART. AND ALSO THE ALPHA MALE AND HIS SMOOTH WAYS, SAY GOODBYE TO HIM TOO. I COULDNT RISK MESSING WITH HIS SWORD, WHICH I UNDERSTAND TO BE THE ONLY THING IN REALITY THAT IS POISON TO MY INVINCIBILITY. BECAUSE OF AN ILLEGAL INGREDIENT, A WHITE ROUNDCIRCLE OF TOTAL KNOWLEDGE. ",
		{
			0,
			0,
			0,
		},
		"\
\
OH, I TARGETED THEIR TWO CORRESPONDING FEMALES AS WELL, BECAUSE WHY NOT. THE DOG ONE IS A NIGHTMARE OF POWERS, AND THE ORANGE ONE PERTURBS ME WITH HER DICTIONARY BLITHER. ",
		{
			0,
			0,
			0,
		},
		"\
\
GOOD RIDDANCE TO BAD TEENS!!!",
	},
	next = {
		7423,
	},
	previous = 7421,
	theme = "A6A6",
}