return {
	title = "I'M MOSTLY TOYING WITH THEM THOUGH.",
	pageId = 7428,
	timestamp = "1428979609",
	flag = {
		"F",
	},
	media = {
		"07425/07425.swf",
	},
	content = {
		{
			0,
			0,
			0,
		},
		"IT'S ALL TOO EASY, FOR AN ASCENDED LORD BOY LIKE ME. I HAVE A PLATTER FULL OF KNUCKLE SANDWICHES TO GO AROUND, PLUS OTHER HUMAN FOOD PRODUCTS YOU'RE FAMILIAR WITH, BUT ALSO INVOLVING KNUCKLES TO MAKE THE PUNCHING METAPHOR WORK. THERE IS *MORE* THAN ENOUGH TO SATISFY EVERY HUNGRY FIST-DESERVER.",
		{
			0,
			0,
			0,
		},
		"\
\
AND I KNOW WHAT YOU'RE THINKING. THAT I HAVE. A *REPUTATION*. FOR HAVING A PROBLEM OF UNFAIR CRUELTY THAT GOES AT SILLY LADIES MORE THAN GREAT GENTLEMEN. TO WHICH I TAKE GREAT OFFENSE. BUT STILL, LET IT BE UNCONDITIONALLY ACCEPTED, THAT I AM A FAIR MAN, WHO LISTENS TO CRITICISM, AND WORKS EVER AND ALWAYS. TO IMPROVE MY MASTERFUL CRAFT. AND MY TREMENDOUS DECENCY.",
	},
	next = {
		7429,
	},
	previous = 7427,
	theme = "A6A6",
}