return {
	title = "SO.",
	pageId = 7429,
	timestamp = "1428980303",
	flag = {
		"F",
	},
	media = {
		"07426/07426.swf",
	},
	content = {
		{
			0,
			0,
			0,
		},
		"I HAVE COMMITTED, THROUGH A PLEDGE OF PERSONAL BEAUTIFICATION. TO TRY DOING LESS MISOGYNY. AND START DOING MORE PROSOGYNY. IN FACT. I FUCKING LOVE SOGYNY! AND I WILL *F*I*G*H*T* ANYONE WHO DISAGREES FROM THAT.",
		{
			0,
			0,
			0,
		},
		"\
\
HENCEWITH. LOOK. ALL BODILY TERRORISM. IS BEING DEALT IN A PRECISELY EQUAL AND RESPECTFUL WAY. BOTH TO FEEBLE HOE, AND TIP-TOP GENT ALIKE.",
	},
	next = {
		7430,
	},
	previous = 7428,
	theme = "A6A6",
}