return {
	title = "IT SEEMS THAT HOPE POWER IS OVERWHELMING.",
	pageId = 7436,
	timestamp = "1429067412",
	flag = {
		"F",
	},
	media = {
		"07433/07433.swf",
	},
	content = {
		{
			0,
			0,
			0,
		},
		"EVEN TO THE CLOCKWORK MANJUNK. IT LOOKED LIKE I THOUGHT I COULD USE MY RAINBOW SEIZURE FIELD TO OVERPOWER HIS MASSIVE GAY HOPE BUBBLE. ALAS. IT WAS MY PERFECTLY JUSTIFIED HUBRIS WHICH BIT ME IN THE ASS, IN THE END. EVEN THOUGH I'M SURE I MUST HAVE KNOWN THIS OUTCOME WAS GOING TO HAPPEN. (IT CAN STILL BE WORTH IT TO GET OWNED. IF IT MEANS HAVING A LOT OF SELF ESTEEMED HUBRIS ABOUT YOURSELF.)",
		{
			0,
			0,
			0,
		},
		"\
\
AND SO, THE ENGLISH BOY DEALS ME MY FIRST DEFEAT EVER, SINCE ASCENDING AS AN INVINCIBLE TECHNICOLOR TIME KID.",
	},
	next = {
		7437,
	},
	previous = 7435,
	theme = "A6A6",
}