return {
	title = "I GET DUNKED AS FUCK.",
	pageId = 7437,
	timestamp = "1429067636",
	flag = {
		"F",
	},
	media = {
		"07434/07434.swf",
	},
	content = {
		{
			0,
			0,
			0,
		},
		"AND LAND SQUARE ON MY BOTTOM. I REMAIN PRONE FOR SEVERAL MINUTES, STARING AT THE CEILING. BLINKING A BIT. PONDERING WHERE THINGS WENT WRONG IN LIFE. HOW I. THE LORD OF TIME. COULD EXPERIENCE SUCH WOEFUL OWNAGE.",
		{
			0,
			0,
			0,
		},
		"\
\
THERE IS NO BODILY HARM OF COURSE. EXCEPT TO MY INCREDIBLE EGO. WHICH IS A FATE WORSE THAN GETTING BROKEN BONES. SO I JUST LIE THERE. THINKING SADLY. ACHIEVING SOME DEPRESSION.",
		{
			0,
			0,
			0,
		},
		"\
\
I'M SURE AT THIS POINT. I TURN TO THOUGHTS OF RESPECT. RESPECT FOR THE PANSIED ASS, PRETTY LEGGED PAGE. AND HIS MAYBE ACCIDENTAL PROWESS. I UNDER MISESTIMATED HIM, AND ADMIRATION HAPPENS IN MY BREAST. MAYBE I'LL JACK HIS SWAGGER TOO, AS HE ONCE DID MINE. MAYBE AFTER A LIFETIME OF UTTERLY DESERVED HUMILIATION, SOBBING, AND SPONTANEOUS URINATION. HE'S EARNED THAT MUCH.",
		{
			0,
			0,
			0,
		},
		"\
\
(THE CLUE HERE IS THAT I STEAL HIS NAME. GOD. YOU THICK, STUPID FUCKS. WHY DO I BOTHER WITH SUB TEXTS, OR FINE LITERATUREY NUANCE. GOD. FUCK! GOD. I TAKE HIS NAME LATER. ENGLISH. THAT'S ME LATER. THAT'S MY NAME. YOU STUPID BRAINLESS FUCKS. HOLY SHIT, YOU ARE DUMB AS BOZOS COME. GOD!!!)",
	},
	next = {
		7438,
	},
	previous = 7436,
	theme = "A6A6",
}