return {
	title = "SO I GET UP. AND...",
	pageId = 7439,
	timestamp = "1429067781",
	flag = {
		"F",
	},
	media = {
		"07436/07436.swf",
	},
	content = {
		{
			0,
			0,
			0,
		},
		"I NEARLY GET THE DROP ON HIM BEFORE HE RELEASES HIS SPELL. BUT THEN... WHAT'S THIS?",
		{
			0,
			0,
			0,
		},
		"\
\
THERE'S A COMMOTION. THE HAUNTING SOUND OF NEIGHS. EXCEPT. THEY'RE ROBOT NEIGHS?",
		{
			0,
			0,
			0,
		},
		"\
\
THAT IS WHEN THE HORSES COME IN TO PLAY. THE GOD DAMN HORSES. HOW TRULY AND UTTERLY IRONIC. THAT MY VERY DEMISE COULD BE IN THE PROXIMITY OF SOME HORSES. WHAT. NO REALLY, WHAT. I DIDN'T FOLLOW THAT. I'M STILL NOT FOLLOWING IT, TO BE HONEST. I'LL HAVE TO THINK IT OVER. I'M THINKING IT OVER *RIGHT NOW*. AND I HAVE A FEELING. I'LL BE THINKING IT OVER FOR THE REST OF MY LIFE. PERHAPS WE ALL WILL.",
		{
			0,
			0,
			0,
		},
		"\
\
WAIT, THEY SHOULD BE ROBOTS. ",
		{
			0,
			0,
			0,
		},
		"\
\
HOLD ON WHILE I PAINT THE HORSES TO LOOK LIKE METAL HORSES. DAMN, THE WORK OF A CRAFTYMAN IS NEVER DONE.",
	},
	next = {
		7440,
	},
	previous = 7438,
	theme = "A6A6",
}