return {
	title = "AND NOW, IF YOU WILL EXCUSE ME.",
	pageId = 7447,
	timestamp = "1429068516",
	flag = {},
	media = {
		"07444",
	},
	content = {
		{
			0,
			0,
			0,
		},
		"I MUST PUT DOWN THE TOYS AND WAYS OF A CHILD. AND CONFRONT THE BIG THINGS OF BECOMING A HUGE MAN. BY DUELING THE SUPREME BEAST OF MY LEGEND LAND, HIS SERPENTINE EMINENCE, YOGURTBONER HIMSELF. I'M ABOUT TO GO FIGHT HIM NOW, SO THIS IS THE LAST TIME YOU WILL EVER HEAR MY EXCELLENT VOICE.",
		{
			0,
			0,
			0,
		},
		"\
\
I WILL DUEL AND CRUSH MY SLITHERING SEXUAL SNAKE BOSS, TO FINISH WHAT I STARTED WHEN I STEPPED MY METAL FOOT INTO THIS CHILDREN'S FARCE. I WILL DO THAT BECAUSE I WANT TO, AND WHEN THAT IS SAID AND DONE, AND YOU SEE ME AT THE PEAK OF A MOUNTAIN OF TROPHIES, RESTING ON MY THRONE OF PRIZES, I WANT TO GET TO TELL YOU THAT I DID WHAT I WANTED TO DO. SO IF YOU REMEMBER JUST ONE THING I SAY, OF SO MANY GREAT THINGS SAID BY ME, THEN PLEASE REMEMBER THIS.",
		{
			0,
			0,
			0,
		},
		"\
\
I WANTED TO PLAY A GAME.",
	},
	next = {
		7448,
	},
	previous = 7446,
	theme = "A6A6",
}